#!/usr/bin/env python3
"""
Kaggle training backend for the mad-lab fine-tuning pipeline.

When `training_env: kaggle` is set in finetune.yaml, this module:
  1. Uploads/versions the training dataset to Kaggle
  2. Generates a self-contained kernel train script (all hyperparams baked in)
  3. Writes kernel-metadata.json
  4. Pushes the kernel to Kaggle

Config in finetune.yaml:
  training_env: kaggle
  kaggle:
    dataset_id:   owner/slug           # Kaggle dataset to upload data to
    kernel_id:    owner/slug           # Kaggle kernel to push
    model_hf_id:  org/model-name       # HuggingFace model ID to download on Kaggle
    model_patches: nemotron_h          # Optional patch set (see PATCH_SETS below)
    # Override hyperparams for Kaggle (more VRAM = longer seqs, higher rank)
    sequence_len: 512
    lora_r: 16
    lora_alpha: 32
    num_epochs: 2

Usage:
  Called automatically by pipeline/train.py when training_env == "kaggle".
  Can also be run standalone:
    python3 pipeline/kaggle_train.py --config run_stock_analyst.yaml --theme themes/stock_analyst
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml


# ---------------------------------------------------------------------------
# Patch set registry
# Each entry is a list of (old_str, new_str) tuples to apply to source files.
# "file" key is relative to the installed transformers package root.
# ---------------------------------------------------------------------------

PATCH_SETS: dict[str, list[dict]] = {
    "nemotron_h": [
        {
            "file": "models/nemotron_h/configuration_nemotron_h.py",
            "patches": [
                (
                    '"*": "attention",\n',
                    '"*": "attention",\n            "-": "mlp",\n',
                ),
                (
                    'valid_types = {"mamba", "attention", "moe"}',
                    'valid_types = {"mamba", "attention", "moe", "mlp"}',
                ),
            ],
        },
        {
            "file": "models/nemotron_h/modeling_nemotron_h.py",
            "patches": [
                (
                    '"moe": NemotronHMoE,\n}',
                    '"moe": NemotronHMoE,\n    "mlp": NemotronHMLP,\n}',
                ),
                (
                    'class NemotronHMLP(nn.Module):\n    def __init__(self, config):',
                    'class NemotronHMLP(nn.Module):\n    def __init__(self, config, **kwargs):',
                ),
                (
                    '"moe": None,\n',
                    '"moe": None,\n                "mlp": None,\n',
                ),
            ],
        },
    ],
}


# ---------------------------------------------------------------------------
# Kernel script template
# All training hyperparams are baked in at generation time.
# ---------------------------------------------------------------------------

KERNEL_TEMPLATE = '''\
#!/usr/bin/env python3
"""
{theme_name} QLoRA fine-tune — generated by mad-lab pipeline.
Model: {model_hf_id}
Dataset: {dataset_id}
"""

import subprocess, sys

def _pip(*pkgs):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *pkgs])

print("Installing dependencies...")
_pip(
    "transformers>=4.51.0",
    "peft>=0.10.0",
    "trl>=0.8.6",
    "bitsandbytes>=0.43.0",
    "datasets>=2.18.0",
    "accelerate>=0.29.0",{extra_pip}
)

import json
from pathlib import Path
import torch
import torch.nn as nn

# ── Torch 2.4.x compat — set_submodule added in 2.5 ──────────────────────────
if not hasattr(nn.Module, "set_submodule"):
    def _set_submodule(self, target, module):
        parts = target.rsplit(".", 1)
        if len(parts) == 1:
            self.add_module(target, module)
        else:
            self.get_submodule(parts[0]).add_module(parts[1], module)
    nn.Module.set_submodule = _set_submodule

{patch_code}
# ── Config ─────────────────────────────────────────────────────────────────────
MODEL_ID     = "{model_hf_id}"
DATASET_SLUG = "{dataset_slug}"
DATA_DIR     = Path(f"/kaggle/input/{{DATASET_SLUG}}/")
OUTPUT_DIR   = Path("/kaggle/working/{output_slug}")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

SEQ_LEN      = {sequence_len}
LORA_R       = {lora_r}
LORA_ALPHA   = {lora_alpha}
LORA_DROPOUT = {lora_dropout}
EPOCHS       = {num_epochs}
BATCH_SIZE   = {micro_batch_size}
GRAD_ACCUM   = {gradient_accumulation_steps}
LR           = {learning_rate}
WARMUP_STEPS = {warmup_steps}

CHAT_TEMPLATE = {chat_template!r}

# ── Tokenizer ──────────────────────────────────────────────────────────────────
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

print(f"Loading tokenizer from {{MODEL_ID}}...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
tokenizer.chat_template = CHAT_TEMPLATE
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# ── Model (4-bit NF4) ──────────────────────────────────────────────────────────
print("Loading model with 4-bit NF4 quantization...")
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
    torch_dtype=torch.bfloat16,
)
{chunk_size_patch}model.config.use_cache = False

# ── LoRA ───────────────────────────────────────────────────────────────────────
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(model, use_gradient_checkpointing={gradient_checkpointing!r})
lora_config = LoraConfig(
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    target_modules="all-linear",
    bias="none",
    task_type="CAUSAL_LM",
)
from peft import get_peft_model
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# Cast bf16 LoRA params to fp32 (AMP scaler requires fp32 trainable params)
for param in model.parameters():
    if param.requires_grad and param.dtype == torch.bfloat16:
        param.data = param.data.to(torch.float32)

# ── Dataset ────────────────────────────────────────────────────────────────────
from datasets import load_dataset

print("\\nLoading dataset...")
dataset = load_dataset("json", data_files={{
    "train":      str(DATA_DIR / "quant_train.jsonl"),
    "validation": str(DATA_DIR / "quant_eval.jsonl"),
}})
print(f"  Train: {{len(dataset[\'train\'])}} | Eval: {{len(dataset[\'validation\'])}}")

ROLE_MAP = {role_map!r}

def _to_messages(sample):
    return [{{"role": ROLE_MAP.get(t["from"], t["from"]), "content": t["value"]}}
            for t in sample["conversations"] if t["from"] in ROLE_MAP]

def _format(sample):
    msgs = _to_messages(sample)
    return {{"text": tokenizer.apply_chat_template(msgs, tokenize=False, add_generation_prompt=False)}}

dataset = dataset.map(_format, remove_columns=dataset["train"].column_names)

# ── Training ───────────────────────────────────────────────────────────────────
from trl import SFTConfig, SFTTrainer

print("\\nStarting training...")
sft_config = SFTConfig(
    output_dir=str(OUTPUT_DIR),
    num_train_epochs=EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRAD_ACCUM,
    learning_rate=LR,
    lr_scheduler_type="cosine",
    warmup_steps=WARMUP_STEPS,
    weight_decay=0.01,
    max_grad_norm=1.0,
    bf16=True,
    fp16=False,
    logging_steps=10,
    eval_strategy="steps",
    eval_steps=200,
    save_strategy="steps",
    save_steps=200,
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    gradient_checkpointing={gradient_checkpointing!r},
    max_seq_length=SEQ_LEN,
    dataset_text_field="text",
    dataloader_num_workers=2,
    optim="paged_adamw_8bit",
    seed=42,
)

trainer = SFTTrainer(
    model=model,
    args=sft_config,
    train_dataset=dataset["train"],
    eval_dataset=dataset["validation"],
    processing_class=tokenizer,
)

trainer.train()

# ── Save ───────────────────────────────────────────────────────────────────────
print(f"\\nSaving adapter to {{OUTPUT_DIR}}...")
trainer.save_model(str(OUTPUT_DIR))
tokenizer.save_pretrained(str(OUTPUT_DIR))

summary = {{
    "theme": "{theme_name}",
    "model_id": MODEL_ID,
    "lora_r": LORA_R,
    "lora_alpha": LORA_ALPHA,
    "sequence_len": SEQ_LEN,
    "num_epochs": EPOCHS,
    "train_samples": len(dataset["train"]),
    "eval_samples": len(dataset["validation"]),
}}
(OUTPUT_DIR / "training_summary.json").write_text(json.dumps(summary, indent=2))
print("Done!\\n" + json.dumps(summary, indent=2))
'''


# ---------------------------------------------------------------------------
# Patch code snippets (inlined into the kernel script)
# ---------------------------------------------------------------------------

PATCH_CODE_NEMOTRON_H = '''\
# ── Nemotron-H patches (applied to installed transformers source) ──────────────
import transformers, importlib
_TF = Path(transformers.__file__).parent

def _patch_file(path, replacements):
    src = path.read_text()
    for old, new in replacements:
        if new in src:
            continue
        if old not in src:
            print(f"  [warn] patch target not found in {path.name}: {old[:50]!r}")
            continue
        src = src.replace(old, new, 1)
        print(f"  [ok] patched {path.name}: {old[:50]!r}")
    path.write_text(src)

print("Applying Nemotron-H patches...")
_patch_file(_TF / "models/nemotron_h/configuration_nemotron_h.py", [
    ('"*": "attention",\\n', '"*": "attention",\\n            "-": "mlp",\\n'),
    ('valid_types = {"mamba", "attention", "moe"}',
     'valid_types = {"mamba", "attention", "moe", "mlp"}'),
])
_patch_file(_TF / "models/nemotron_h/modeling_nemotron_h.py", [
    ('"moe": NemotronHMoE,\\n}', '"moe": NemotronHMoE,\\n    "mlp": NemotronHMLP,\\n}'),
    ('class NemotronHMLP(nn.Module):\\n    def __init__(self, config):',
     'class NemotronHMLP(nn.Module):\\n    def __init__(self, config, **kwargs):'),
    ('"moe": None,\\n', '"moe": None,\\n                "mlp": None,\\n'),
])
importlib.invalidate_caches()
print("Patches applied.\\n")

'''

PATCH_EXTRA_DEPS: dict[str, list[str]] = {
    "nemotron_h": ["mamba-ssm", "causal-conv1d"],
}

CHUNK_SIZE_PATCH = '''\
# Reduce Mamba-2 chunk_size 256→64 (cuts G_intermediate 16×)
if hasattr(model.config, "chunk_size") and model.config.chunk_size > 64:
    print(f"chunk_size: {model.config.chunk_size} → 64")
    model.config.chunk_size = 64
for _m in model.modules():
    if hasattr(_m, "chunk_size"):
        _m.chunk_size = 64

'''

# Models that don't support gradient checkpointing
NO_GRAD_CHECKPOINT_PATCHES = {"nemotron_h"}


# ---------------------------------------------------------------------------
# Chat template (matches pipeline/train.py)
# ---------------------------------------------------------------------------

CHAT_TEMPLATES = {
    "chatml": (
        "{% for message in messages %}"
        "{% if message['role'] == 'system' %}<|im_start|>system\n{{ message['content'] }}<|im_end|>\n"
        "{% elif message['role'] == 'user' %}<|im_start|>user\n{{ message['content'] }}<|im_end|>\n"
        "{% elif message['role'] == 'assistant' %}<|im_start|>assistant\n{{ message['content'] }}<|im_end|>\n"
        "{% endif %}{% endfor %}"
        "{% if add_generation_prompt %}<|im_start|>assistant\n{% endif %}"
    ),
    "llama3": (
        "{% for message in messages %}"
        "<|start_header_id|>{{ message['role'] }}<|end_header_id|>\n\n"
        "{{ message['content'] }}<|eot_id|>"
        "{% endfor %}"
        "{% if add_generation_prompt %}<|start_header_id|>assistant<|end_header_id|>\n\n{% endif %}"
    ),
    "mistral": (
        "{% for message in messages %}"
        "{% if message['role'] == 'user' %}[INST] {{ message['content'] }} [/INST]"
        "{% elif message['role'] == 'assistant' %}{{ message['content'] }}</s>"
        "{% endif %}{% endfor %}"
    ),
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _run(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    print(f"  $ {' '.join(cmd)}")
    return subprocess.run(cmd, check=check, capture_output=False)


def _kaggle_dataset_exists(dataset_id: str) -> bool:
    result = subprocess.run(
        ["kaggle", "datasets", "status", dataset_id],
        capture_output=True, text=True,
    )
    return result.returncode == 0


def upload_dataset(dataset_id: str, train_data: str, eval_data: str) -> None:
    """Upload or version the training dataset on Kaggle."""
    owner, slug = dataset_id.split("/", 1)

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)

        # Copy data files
        shutil.copy(train_data, tmp_path / Path(train_data).name)
        shutil.copy(eval_data,  tmp_path / Path(eval_data).name)

        # Write dataset-metadata.json
        metadata = {
            "title": slug.replace("-", " ").title(),
            "id": dataset_id,
            "licenses": [{"name": "CC0-1.0"}],
        }
        (tmp_path / "dataset-metadata.json").write_text(json.dumps(metadata, indent=2))

        if _kaggle_dataset_exists(dataset_id):
            print(f"  Versioning existing dataset {dataset_id}...")
            _run(["kaggle", "datasets", "version", "-p", str(tmp_path),
                  "-m", "Updated training data", "--dir-mode", "zip"])
        else:
            print(f"  Creating new dataset {dataset_id}...")
            _run(["kaggle", "datasets", "create", "-p", str(tmp_path),
                  "--dir-mode", "zip"])

    print(f"  Dataset ready: {dataset_id}")


def generate_kernel(
    theme_name: str,
    ft_cfg: dict,
    kaggle_cfg: dict,
    theme_dir: Path,
    kernel_dir: Path,
) -> None:
    """Write train.py and kernel-metadata.json into kernel_dir."""

    model_patches = kaggle_cfg.get("model_patches", "")
    dataset_id    = kaggle_cfg["dataset_id"]
    kernel_id     = kaggle_cfg["kernel_id"]
    model_hf_id   = kaggle_cfg["model_hf_id"]

    # Dataset slug (last part of "owner/slug")
    dataset_slug = dataset_id.split("/", 1)[1]

    # Kernel output slug (last part of kernel_id)
    output_slug = kernel_id.split("/", 1)[1]

    # Merge Kaggle overrides on top of base ft_cfg
    sequence_len  = kaggle_cfg.get("sequence_len",  ft_cfg.get("sequence_len", 512))
    lora_r        = kaggle_cfg.get("lora_r",        ft_cfg.get("lora_r", 16))
    lora_alpha    = kaggle_cfg.get("lora_alpha",    ft_cfg.get("lora_alpha", 32))
    lora_dropout  = kaggle_cfg.get("lora_dropout",  ft_cfg.get("lora_dropout", 0.05))
    num_epochs    = kaggle_cfg.get("num_epochs",    ft_cfg.get("num_epochs", 2))
    batch_size    = kaggle_cfg.get("micro_batch_size", ft_cfg.get("micro_batch_size", 1))
    grad_accum    = kaggle_cfg.get("gradient_accumulation_steps",
                                   ft_cfg.get("gradient_accumulation_steps", 8))
    learning_rate = kaggle_cfg.get("learning_rate", ft_cfg.get("learning_rate", 2e-4))
    warmup_steps  = kaggle_cfg.get("warmup_steps",  ft_cfg.get("warmup_steps", 50))

    # Chat template from theme
    theme_cfg_path = theme_dir / "theme.yaml"
    theme_cfg = yaml.safe_load(theme_cfg_path.read_text()) if theme_cfg_path.exists() else {}
    out_fmt   = theme_cfg.get("output", {})
    chat_template_name = out_fmt.get("chat_template", "chatml")
    chat_template = CHAT_TEMPLATES.get(chat_template_name, CHAT_TEMPLATES["chatml"])

    # Role map from theme
    role_map = {
        out_fmt.get("system_role",    "system"): "system",
        out_fmt.get("user_role",      "human"):  "user",
        out_fmt.get("assistant_role", "gpt"):    "assistant",
    }

    # Patch code block
    patch_code = ""
    if model_patches in PATCH_CODE_SNIPPETS:
        patch_code = PATCH_CODE_SNIPPETS[model_patches]

    # Extra pip deps
    extra_pip = ""
    if model_patches in PATCH_EXTRA_DEPS:
        for dep in PATCH_EXTRA_DEPS[model_patches]:
            extra_pip += f'\n    "{dep}",'

    # chunk_size patch (Mamba-2 models only)
    chunk_size_patch = CHUNK_SIZE_PATCH if model_patches == "nemotron_h" else ""

    # Gradient checkpointing
    gradient_checkpointing = model_patches not in NO_GRAD_CHECKPOINT_PATCHES

    script = KERNEL_TEMPLATE.format(
        theme_name=theme_name,
        model_hf_id=model_hf_id,
        dataset_id=dataset_id,
        dataset_slug=dataset_slug,
        output_slug=output_slug,
        sequence_len=sequence_len,
        lora_r=lora_r,
        lora_alpha=lora_alpha,
        lora_dropout=lora_dropout,
        num_epochs=num_epochs,
        micro_batch_size=batch_size,
        gradient_accumulation_steps=grad_accum,
        learning_rate=learning_rate,
        warmup_steps=warmup_steps,
        chat_template=chat_template,
        role_map=role_map,
        patch_code=patch_code,
        extra_pip=extra_pip,
        chunk_size_patch=chunk_size_patch,
        gradient_checkpointing=gradient_checkpointing,
    )

    (kernel_dir / "train.py").write_text(script)

    # kernel-metadata.json
    owner, kernel_slug = kernel_id.split("/", 1)
    metadata = {
        "id": kernel_id,
        "title": f"{theme_name.replace('_', ' ').title()} QLoRA Fine-tune",
        "code_file": "train.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": True,
        "enable_tpu": False,
        "enable_internet": True,
        "dataset_sources": [dataset_id],
        "competition_sources": [],
        "kernel_sources": [],
    }
    (kernel_dir / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2))

    print(f"  Kernel script written: {kernel_dir / 'train.py'}")
    print(f"  Kernel metadata written: {kernel_dir / 'kernel-metadata.json'}")


# Mapping from patch name → code snippet to embed in kernel
PATCH_CODE_SNIPPETS: dict[str, str] = {
    "nemotron_h": PATCH_CODE_NEMOTRON_H,
}


# ---------------------------------------------------------------------------
# Main entry point (called from pipeline/train.py or standalone)
# ---------------------------------------------------------------------------

def run(ft_cfg: dict, run_cfg: dict, train_data: str, eval_data: str, theme_dir: Path) -> None:
    """Package + upload dataset, generate + push kernel."""
    kaggle_cfg  = ft_cfg.get("kaggle", {})
    dataset_id  = kaggle_cfg.get("dataset_id")
    kernel_id   = kaggle_cfg.get("kernel_id")

    if not dataset_id or not kernel_id:
        print("Error: finetune.yaml kaggle.dataset_id and kaggle.kernel_id are required")
        sys.exit(1)

    theme_name = theme_dir.name

    # Use a persistent kernel dir under the theme so the user can inspect it
    kernel_dir = theme_dir / "kaggle_kernel"
    kernel_dir.mkdir(exist_ok=True)

    print(f"\n{'='*60}")
    print(f"  Kaggle training backend")
    print(f"  theme    : {theme_name}")
    print(f"  dataset  : {dataset_id}")
    print(f"  kernel   : {kernel_id}")
    print(f"  train    : {train_data}")
    print(f"  eval     : {eval_data}")
    print(f"{'='*60}\n")

    # 1. Upload / version dataset
    print("[1/3] Uploading dataset to Kaggle...")
    upload_dataset(dataset_id, train_data, eval_data)

    # 2. Generate kernel
    print("\n[2/3] Generating kernel script...")
    generate_kernel(theme_name, ft_cfg, kaggle_cfg, theme_dir, kernel_dir)

    # 3. Push kernel
    print("\n[3/3] Pushing kernel to Kaggle...")
    _run(["kaggle", "kernels", "push", "-p", str(kernel_dir)])

    owner, slug = kernel_id.split("/", 1)
    url = f"https://www.kaggle.com/code/{owner}/{slug}"
    print(f"\nKernel submitted! Monitor at: {url}")
    print("Download adapter after completion:")
    print(f"  kaggle kernels output {kernel_id}")


# ---------------------------------------------------------------------------
# Standalone entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Push training job to Kaggle")
    parser.add_argument("--config", required=True, help="Run config yaml")
    parser.add_argument("--theme",  required=True, help="Path to theme directory")
    args = parser.parse_args()

    base = Path(__file__).parent.parent

    config_path = Path(args.config)
    if not config_path.is_absolute():
        config_path = base / args.config

    theme_path = Path(args.theme)
    if not theme_path.is_absolute():
        theme_path = base / args.theme

    with open(config_path) as f:
        run_cfg = yaml.safe_load(f)

    ft_path = theme_path / "finetune.yaml"
    ft_cfg = yaml.safe_load(ft_path.read_text()) if ft_path.exists() else run_cfg.get("finetune", {})

    train_data = ft_cfg.get("train_data") or str(Path(run_cfg["output_dir"]) / "train.jsonl")
    eval_data  = ft_cfg.get("eval_data")  or str(Path(run_cfg["output_dir"]) / "eval.jsonl")

    run(ft_cfg, run_cfg, train_data, eval_data, theme_path)


if __name__ == "__main__":
    main()
